# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-01 01:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogo', '0002_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabecera',
            fields=[
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('distribuidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Distribuidor')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Empresa')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(max_length=9)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabecera', to='catalogo.Cabecera')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Producto')),
            ],
        ),
        migrations.RemoveField(
            model_name='compra',
            name='distribuidor',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='trabajador',
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
    ]
