# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-01 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_auto_20161031_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
